services:
  # ---------- Observability ----------
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otelcol-config.yaml"]
    volumes:
      - ./backend/otelcol-config.yaml:/etc/otelcol-config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "9464:9464"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./backend/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  loki:
    image: grafana/loki:3.5.8
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./backend/loki-config.yaml:/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  tempo:
    image: grafana/tempo:latest
    command: -config.file=/etc/tempo/tempo.yaml
    volumes:
      - ./backend/tempo.yaml:/etc/tempo/tempo.yaml
    ports:
      - "3200:3200"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - loki
      - tempo

  # ---------- Shared infra ----------
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  # ---------- ML Service (Python) ----------
  ml-service:
    build: ./ml-service
    container_name: proscale-ml
    ports:
      - "8000:8000"
    
  # ---------- Backend (Node) ----------

  backend:
    build: ./backend
    container_name: proscale-backend
    ports:
      - "3004:3004"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_SERVICE_NAME=pro-scale-service
      - OTEL_LOGS_EXPORTER=otlp
      - REDIS_URL=redis://redis:6379
      - PROM_URL=http://prometheus:9090/api/v1/query
      - ML_URL=http://ml-service:8000/predict
    depends_on:
      - redis
      - otel-collector
      - prometheus
      - ml-service