services:
  my-node-app:
    build:
      context: .
      target: builder
    env_file:
     - .env.development
    command: npm run dev
    environment:
      - NODE_ENV=development
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules/

        - action: rebuild
          path: ./package.json